### PR TITLE
Sync with upstream.

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by jrick** [comment]
Why aren't we just using glide?

**Comment by jcvernaleo** [comment]
Unless we are making changes locally it really doesn't make a lot of sense to keep this fork up when glide solves the problem as @jrick said.

**Comment by dajohi** [comment]
I can agree to use glide.  @davecgh?

**Comment by davecgh** [comment]
I'm fine with switching glide over to use the upstream one directly, but I'd prefer to continue to maintain this fork for a while as well since older versions still need it.

**Comment by davecgh** [comment]
As far as the PR.  I want to review the commits before accepting it or not.  It's important to do the same even if glide is used.

**Comment by jrick** [comment]
If by maintain this fork you mean just leave it alone, then sure, but we shouldn't be updating it then since the older versions aren't locking the version with glide.

**Comment by davecgh** [comment]
Yes, I mean leave it alone after this PR is merged.

**Comment by jcvernaleo** [comment]
Since we aren't using seelog or this fork any more just going to close this PR.

**Pull request closed without merging**
